### ISSUE TITLE
Recommended version to use?

### ISSUE THREAD

**Issue by abeforgit** [lblod/acmidm-login-service#4]
We've been running 0.8.0 in GN for as long as I know, and it's been working fine as far as I can tell.
As part of a maintenance run I noticed theres up to 0.9.2 in stable releases and 0.10.0 in a 2-year old beta. I don't understand enough about this service to put the commit messages into context, but e.g. [9fb54904337b1bdce3cd8b4886637a66bfe16afe](https://github.com/lblod/acmidm-login-service/commit/9fb54904337b1bdce3cd8b4886637a66bfe16afe) seems like a bugfix to me.

Maybe it's time to cut a new stable 0.10.0 release? and if there's things to consider when upgrading, maybe we could include those in the release notes?

**Comment by erikap** [comment]
Hi @abeforgit  stable releases are available now. Probably best to use the most recent one v0.12.0 which contains up-to-date dependencies.
